### ISSUE TITLE
Questions for lambada_val

### ISSUE THREAD

**Issue by ponytaill** [lpyhdzx/DecoQuant_code#1]
Hi, could you share your dataset's structure?https://github.com/lpyhdzx/DecoQuant_code/blob/7184cba73f7dfec85ccea8a53b02425ab8218704/language_model/examples/smoothquant_llama_demo.py#L87

I tried to load lambada from huggingface, but got error when ran smoothquant_llama_demo.py
Traceback (most recent call last):
  File "/root/autodl-tmp/DecoQuant_code/language_model/examples/smoothquant_llama_demo.py", line 94, in <module>
    acc_fp16 = evaluator.evaluate(model_fp16)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/DecoQuant_code/language_model/examples/smoothquant_llama_demo.py", line 59, in evaluate
    input_ids = batch['input_ids'].to(self.device).unsqueeze(0)
TypeError: string indices must be integers

**Comment by ponytaill** [comment]
> Hi, could you share your dataset's structure?
> 
> https://github.com/lpyhdzx/DecoQuant_code/blob/7184cba73f7dfec85ccea8a53b02425ab8218704/language_model/examples/smoothquant_llama_demo.py#L87
> 
> I tried to load lambada from huggingface, but got error when ran smoothquant_llama_demo.py Traceback (most recent call last): File "/root/autodl-tmp/DecoQuant_code/language_model/examples/smoothquant_llama_demo.py", line 94, in acc_fp16 = evaluator.evaluate(model_fp16) File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/autodl-tmp/DecoQuant_code/language_model/examples/smoothquant_llama_demo.py", line 59, in evaluate input_ids = batch['input_ids'].to(self.device).unsqueeze(0) TypeError: string indices must be integers

I figured it out. You have to use `dataset = load_dataset("/root/autodl-tmp/lambada_val/plain_text", split="validation")` instead if you download lambada from huggingface directly.
